language: python
sudo: false

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"

matrix:
  include:
    - env: TOXENV=flake8

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: false
