language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"

matrix:
  include:
    - env: TOXENV=flake8

before_install:
  - sudo apt-get -y install libsqlcipher0

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: false
